name: "dbt_stat_test"
version: "0.1.0"

require-dbt-version: [">=1.1.0", "<2.0.0"]
config-version: 2

model-paths: ["models"]
clean-targets: ["target", "dbt_modules"]
macro-paths: ["macros"]
flags:
  require_generic_test_arguments_property: true